### ISSUE TITLE
Having issues on download / guide

### ISSUE THREAD

**Issue by ashhhk** [TheKawaiiNeko/BF4-External#1]
Hi, how do you download the hack? 

i found it on unknown cheats.
https://www.unknowncheats.me/forum/downloads.php?do=file&id=40960

There is no way i can download it, can you show me a guide or guide me through discord? 
i have been around here for few hours until now...

Thank you

**Comment by NCZLL** [comment]
Step 1. Register a UC account
Step 2. Download

It's not difficult
