### ISSUE TITLE
Bhuh, what happened here ?

### ISSUE THREAD

**Issue by DestroyerDarkNess** [TheKawaiiNeko/BF4-External#4]
Edit : It works perfectly, great job, but it drastically reduces the fps of the game.  Even though the trick says 40 - 50 fps, it actually goes at about 10. super lag and the models look like plasticine. The aimbot doesn't work, it points directly into the sky.

![image](https://github.com/TheKawaiiNeko/BF4-External/assets/32405118/07b2d8b1-06e0-445f-8cc9-9a9c6a7926ee)

**Comment by TheKawaiiNeko** [comment]
upgrade your pc
Recommendation: Ryzem9 5900X, 64GB, RTX3080Ti

**Comment by DestroyerDarkNess** [comment]
🤣🤣🤣

I thought it was a performance problem with your cheat, written for high-resource computers. so I started to convert all your code to C# - .Net Framework..... but I had some problems:


https://github.com/TheKawaiiNeko/BF4-External/assets/32405118/018c89b5-4cb9-4f85-a6e2-e6323d9b543b

**Comment by DestroyerDarkNess** [comment]
Okay, I converted your cheat to [c#](https://github.com/DestroyerDarkNess/BF4-External), and it doesn't eat fps. 😊  Also, my overlay works based on dx9, while yours is dx11.
